# Generated by Django 5.0.3 on 2024-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телеграм'),
        ),
    ]
