# Generated by Django 5.0.3 on 2024-03-11 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_remove_habit_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='start_point',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 18, 11, 0, 72794, tzinfo=datetime.timezone.utc), verbose_name='Когда?'),
        ),
    ]
