# Generated by Django 5.0.3 on 2024-03-12 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_duration_alter_habit_start_point_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('id',), 'verbose_name': 'привычка', 'verbose_name_plural': 'привычек'},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_point',
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 12), verbose_name='Когда?'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(9, 48, 51, 269663), verbose_name='Во сколько?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(default='00:00', verbose_name='Выполнять мм:сс'),
        ),
    ]
